apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-101
  name: kube-101
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-101
  strategy: {}
  template:
    metadata:
      labels:
        app: kube-101
    spec:
      containers:
      - image: quay.io/sammarland_rh/node-kube-101:latest
        name: node-kube-101
        resources: {}
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: app-config
status: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  BODY_TEXT: Testing out Kubernetes
  EVENT_NAME: Kubernetes 101
  ORG: NWG - Development
  ORG_FULL: Natwest Group
  SLEEP_TIME: "500"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-101-service 
spec:
  selector:
    app: kube-101 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kube-101
spec:
  host: kube-101-nwg-demo.apps.sandy.demolab.local
  port:
    targetPort: 3000
  to:
    kind: Service
    name: kube-101-service
    weight: 100
  wildcardPolicy: None