apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kube-101
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: kube-101
  targetCPUUtilizationPercentage: 40
